language: python
sudo: false

python:
  - 2.7
  - pypy
  - 3.4
  - 3.5
  - 3.6
  - 3.8-dev
  - pypy3

matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7
      dist: xenial
      addons:
        apt:
          packages:
            - python-coverage
      after_success:
        - codecov
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2
      language: shell
    - name: "Python 3.7.3 on Windows"
      os: windows
      language: shell
      before_install: choco install python
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

script:
  - chmod +x log_clean.sh && ./log_clean.sh
  - python3 log_cruncher.py --cov=codecov || python log_cruncher.py --cov=codecov